name: rm and mv test
on:
  workflow_dispatch:
defaults:
  run:
    shell: cmd

jobs:
  test:
    strategy:
      matrix:
        osver: [2019, 2022]
        isolation: [process, hyperv]
    runs-on: windows-${{ matrix.osver }}
    steps:
      - uses: actions/checkout@v2
      - name: run windows-${{ matrix.osver }} container using ${{ matrix.isolation }} isolation
        run: |
          mkdir binded_dir
          docker run --isolation=${{ matrix.isolation }} -v "${{ github.workspace }}\binded_dir:c:\binded_dir" -v "c:\msys64:c:\msys64" -v "${{ github.workspace }}\rm_and_mv:c:\rm_and_mv" mcr.microsoft.com/windows/servercore:ltsc${{ matrix.osver }} cmd.exe /s /c "c:\rm_and_mv\test.cmd"

